// trainee_ai_assistant_translations.js
'use strict';
document.addEventListener('DOMContentLoaded', function() {
    const pageTranslations = {
        he: {
            trainee_ai_assistant_page_title: "עוזר AI - פלטפורמת סימולציות סייבר",
            ai_assistant_header: "עוזר AI לאבטחה",
            ai_assistant_subtitle: "שאל שאלות, בקש הבהרות או קבל הכוונה מהעוזר הווירטואלי שלך.",
            ai_chat_input_placeholder: "שאל את העוזר הווירטואלי...",
            send_ai_chat_message_button_tooltip: "שלח הודעה לעוזר",
            // Example initial AI greeting
            ai_greeting_message: "שלום! אני עוזר ה-AI של פלטפורמת הסימולציות, מבוסס Cisco Foundation AI. אני כאן כדי לסייע לך בניתוח איומים, הבנת פרוטוקולי אבטחה וקבלת הכוונה בתרחישי סייבר.",
            // Example user questions and AI responses (for JS mock data)
            user_q1_ai: "מהי המשמעות של IOC מסוג 'Hash SHA256'?",
            ai_response_q1: "Hash SHA256 הוא חתימה קריפטוגרפית ייחודית באורך 256 ביט של קובץ או נתון. שינוי קטן בקלט יגרום ל-hash שונה לחלוטין. הוא משמש לזיהוי ודאי של קבצים ידועים (למשל, נוזקות) או לאימות שלמות נתונים.",
            user_q2_ai: "אילו כלים יכולים לעזור לי לנתח קובץ חשוד שבודדתי?",
            ai_response_q2: "לניתוח קובץ חשוד בסביבה מבוקרת, תוכל לשקול שימוש בכלים כמו: VirusTotal (לסריקה מול מנועי אנטי-וירוס מרובים), IDA Pro או Ghidra (לדיסאסמבלי וניתוח קוד), Wireshark (לניתוח תעבורת רשת שהקובץ מייצר), או סביבת Sandbox ייעודית כמו Cuckoo Sandbox.",
            user_q3_ai: "כיצד אוכל לבדוק אם כתובת IP מסוימת היא זדונית?",
            ai_response_q3: "ישנם מספר מאגרי מוניטין מקוונים שניתן לבדוק בהם כתובות IP, כגון: VirusTotal (בודק גם IPs ודומיינים), AbuseIPDB, IBM X-Force Exchange, ו-Talos Intelligence. בנוסף, חיפוש ה-IP במנועי חיפוש עם מילות מפתח כמו 'malware', 'C2' יכול לעיתים לחשוף מידע.",
            no_ai_messages_yet: "התחל שיחה עם עוזר ה-AI.", // If chat is empty
            // Navigation buttons
            go_back_to_communication: "חזור לתקשורת צוותית",
            go_to_mitre_attack_view_from_ai: "המשך לשלבי תקיפה (MITRE)",
            example_questions: "שאלות לדוגמא שאפשר לשאול:",
            cisco_foundation_ai: "Cisco Foundation AI",
            security_expert: "מומחה באבטחת מידע"
        },
        en: {
            trainee_ai_assistant_page_title: "AI Assistant - Cyber Simulation Platform",
            ai_assistant_header: "Security AI Assistant",
            ai_assistant_subtitle: "Ask questions, request clarifications, or get guidance from your virtual assistant.",
            ai_chat_input_placeholder: "Ask the virtual assistant...",
            send_ai_chat_message_button_tooltip: "Send message to assistant",
            ai_greeting_message: "Hello! I'm the simulation platform AI assistant, powered by Cisco Foundation AI. I'm here to help you with threat analysis, security protocols, and cyber scenario guidance.",
            user_q1_ai: "What is the significance of an IOC typu 'SHA256 Hash'?",
            ai_response_q1: "A SHA256 hash is a unique 256-bit cryptographic signature of a file or data. A small change in the input will result in a completely different hash. It's used for definitive identification of known files (e.g., malware) or to verify data integrity.",
            user_q2_ai: "What tools can help me analyze a suspicious file I've isolated?",
            ai_response_q2: "For analyzing a suspicious file in a controlled environment, you might consider tools like: VirusTotal (for scanning against multiple antivirus engines), IDA Pro or Ghidra (for disassembly and code analysis), Wireshark (for analyzing network traffic generated by the file), or a dedicated Sandbox environment like Cuckoo Sandbox.",
            user_q3_ai: "How can I check if a specific IP address is malicious?",
            ai_response_q3: "There are several online reputation databases where you can check IP addresses, such as: VirusTotal (also checks IPs and domains), AbuseIPDB, IBM X-Force Exchange, and Talos Intelligence. Additionally, searching for the IP in search engines with keywords like 'malware' or 'C2' can sometimes reveal information.",
            no_ai_messages_yet: "Start a conversation with the AI assistant.",
            // Navigation buttons
            go_back_to_communication: "Back to Team Communication",
            go_to_mitre_attack_view_from_ai: "Continue to Attack Flow (MITRE)",
            example_questions: "Example questions you can ask:",
            cisco_foundation_ai: "Cisco Foundation AI",
            security_expert: "Security Expert"
        }
    };
    if (window.translations) {
        if (window.translations.he) {
            Object.assign(window.translations.he, pageTranslations.he);
        } else {
            window.translations.he = pageTranslations.he;
        }
        if (window.translations.en) {
            Object.assign(window.translations.en, pageTranslations.en);
        } else {
            window.translations.en = pageTranslations.en;
        }
        if (typeof window.applyTranslationsGlobal === 'function') {
            // console.log('trainee_ai_assistant_translations.js: Calling applyTranslationsGlobal after merge.');
            window.applyTranslationsGlobal();
        }
    } else {
        console.error('trainee_ai_assistant_translations.js: Global translations object (window.translations) not found.');
        window.translations = pageTranslations; // Fallback
        if (typeof window.applyTranslationsGlobal === 'function') {
            window.applyTranslationsGlobal();
        }
    }
});